version: '3.8'

services:
  throttler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: throttler
    # Privileged is required for taskset (cpu affinity) and stress-ng features
    privileged: true
    restart: always
    volumes:
      # Allow easy access to the throttle control file from the host if needed
      - /tmp/throttler/global_throttle:/tmp/global_throttle
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
